# Generated by Django 5.2.6 on 2025-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='BUY', max_length=50)),
                ('wallet', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('crypto_symbol', models.CharField(default='BTC', max_length=10)),
                ('crypto_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('usd_value_at_entry', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gas_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
